import Link from "next/link";
import { ArrowRight, Bot, Check, ChevronRight, CircleDot, Clock3, Layers3, MessageSquareText, Workflow } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Container } from "@/components/layout/container";
import { solutions, useCases } from "@/content/site";

export function Hero() { return <section className="hero"><Container className="grid items-center gap-16 lg:grid-cols-[1.05fr_.95fr]"><div><p className="eyebrow">Empleados Digitales con IA</p><h1>Haz avanzar tu empresa con <em>inteligencia</em> que trabaja contigo.</h1><p className="lead">Diseñamos e implementamos soluciones de inteligencia artificial que atienden clientes, automatizan procesos y ayudan a tu equipo a trabajar mejor.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button href="/contacto">Solicitar una demo <ArrowRight size={16}/></Button><Button href="/soluciones" variant="secondary">Conocer las soluciones</Button></div></div><SystemVisual /></Container></section>; }
function SystemVisual() { return <div className="system-visual" aria-hidden="true"><div className="system-orbit orbit-one"/><div className="system-orbit orbit-two"/><div className="system-core"><Bot size={33}/><span>Kalivur IA</span></div><div className="system-node node-a"><MessageSquareText size={16}/> Consulta</div><div className="system-node node-b"><Workflow size={16}/> Flujo</div><div className="system-node node-c"><Layers3 size={16}/> Equipo</div></div>; }
export function ValueStrip() { return <section className="value-strip"><Container className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{["Atención continua", "Procesos automatizados", "Conexión entre herramientas", "Implementación adaptada"].map(x => <div key={x}><Check size={17}/><span>{x}</span></div>)}</Container></section>; }
export function Problems() { const ps=["Clientes que esperan demasiado por una respuesta.","Consultas repetitivas que consumen tiempo valioso.","Reservas o ventas que se pierden entre mensajes.","Información dispersa en distintas herramientas.","Equipos sobrecargados con tareas manuales."]; return <section className="section"><Container className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">El reto diario</p><h2>El trabajo que frena a tu equipo no debería quedarse igual.</h2></div><div className="problem-list">{ps.map((p,i)=><div key={p}><span>0{i+1}</span><p>{p}</p><ChevronRight size={18}/></div>)}</div></Container></section>; }
export function Solutions() { return <section className="section section-muted"><Container><p className="eyebrow">Cómo ayudamos</p><h2 className="max-w-2xl">Tecnología que se adapta al ritmo de tu operación.</h2><div className="card-grid mt-12">{solutions.map((x,i)=>{const Icon=[MessageSquareText,Workflow,Bot][i]; return <article className="feature-card" key={x.title}><Icon/><h3>{x.title}</h3><p>{x.text}</p><Link href="/soluciones">Explorar solución <ArrowRight size={15}/></Link></article>})}</div></Container></section>; }
export function Process() { return <section className="section"><Container><div className="flex flex-col justify-between gap-5 md:flex-row"><div><p className="eyebrow">Nuestro enfoque</p><h2>Una solución que empieza por entender tu negocio.</h2></div><p className="max-w-sm text-[var(--muted)]">Kalivur acompaña el proceso de principio a fin: desde el diagnóstico hasta la mejora continua.</p></div><div className="process-grid mt-12">{["Diagnóstico","Diseño de la solución","Implementación","Optimización"].map((x,i)=><div key={x}><span>0{i+1}</span><h3>{x}</h3><p>{["Entendemos procesos, prioridades y oportunidades.","Definimos una propuesta útil para tu operación.","Construimos y conectamos cada flujo necesario.","Revisamos, ajustamos y hacemos evolucionar la solución."][i]}</p></div>)}</div></Container></section>; }
export function UseCases() { return <section className="section section-dark"><Container><p className="eyebrow">Casos de uso</p><h2>Una base más ágil para cada tipo de servicio.</h2><div className="use-case-grid mt-12">{useCases.map((x,i)=><Link key={x} href="/casos-de-uso"><span>0{i+1}</span><h3>{x}</h3><ArrowRight size={19}/></Link>)}</div></Container></section>; }
export function ProductPreview() { return <section className="section"><Container className="grid items-center gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Vista de demostración</p><h2>Una mirada clara a lo que está en movimiento.</h2><p className="mt-5 text-[var(--muted)]">Una futura vista central para acompañar conversaciones, solicitudes y la actividad de tu Empleado Digital.</p><p className="mt-6 inline-flex items-center gap-2 text-sm text-[var(--muted)]"><CircleDot size={15}/> Datos ilustrativos · Próximamente</p></div><Dashboard /></Container></section>; }
function Dashboard(){return <div className="dashboard"><div className="dash-nav"><span className="dash-logo">K.</span><span className="dash-line active"/><span className="dash-line"/><span className="dash-line"/></div><div className="dash-main"><div className="dash-heading"><div><small>Vista general</small><strong>Buenos días, equipo</strong></div><span className="status"><i/> Empleado Digital activo</span></div><div className="metrics"><Metric title="Conversaciones atendidas" value="—" icon={<MessageSquareText/>}/><Metric title="Solicitudes y citas" value="—" icon={<Clock3/>}/><Metric title="Por revisar" value="—" icon={<CircleDot/>}/></div><div className="dash-bottom"><div className="chart"><small>Actividad reciente</small><div className="bars">{[32,54,42,76,51,88,65,97,72,82].map((x,i)=><i key={i} style={{height:`${x}%`}}/>)}</div></div><div className="activity"><small>Necesitan atención humana</small><p><i/> Conversación pendiente</p><p><i/> Solicitud nueva</p></div></div></div></div>}
function Metric({title,value,icon}:{title:string;value:string;icon:React.ReactNode}){return <div><span>{icon}</span><small>{title}</small><strong>{value}</strong></div>}
export function Benefits() { const b=["Responder con mayor rapidez","Mantener una atención consistente","Reducir tareas repetitivas","Organizar mejor la información","Ayudar al equipo humano","Acompañar el crecimiento del negocio"]; return <section className="section section-muted"><Container><p className="eyebrow">Lo que habilita</p><h2>Más espacio para el trabajo que realmente importa.</h2><div className="benefit-grid mt-10">{b.map(x=><div key={x}><Check size={18}/>{x}</div>)}</div></Container></section>; }
export function FinalCta(){return <section className="cta-section"><Container><div><p className="eyebrow">El siguiente paso</p><h2>Conversemos sobre lo que tu empresa puede automatizar.</h2><p>Analizamos tus procesos y diseñamos una solución de IA adaptada a tu operación.</p><Button href="/contacto">Solicitar una demo <ArrowRight size={16}/></Button></div></Container></section>;}
