import Link from "next/link";
import { ArrowUpRight, Bot, CalendarCheck, Check, CircleDot, MessagesSquare, Route, ShieldCheck, Sparkles, Workflow } from "lucide-react";
import { HeroVisual } from "@/components/sections/hero-visual";
import { PrimaryCta } from "@/components/ui/cta";
import { benefits, solutions, useCases } from "@/content/site";

const problems = ["Consultas sin responder", "Tareas repetitivas", "Citas y seguimientos manuales", "Información dispersa entre herramientas"];
const steps = [
  ["01", "Diagnóstico", "Entendemos dónde se pierde tiempo, información u oportunidades."],
  ["02", "Diseño del empleado digital", "Definimos qué debe hacer, cuándo actuar y cuándo escalar a una persona."],
  ["03", "Integración e implementación", "Conectamos el flujo con las herramientas que forman parte de tu operación."],
  ["04", "Medición y mejora continua", "Revisamos el funcionamiento y ajustamos el proceso con evidencia operativa."],
];

export default function Home() {
  return <>
    <section className="container-shell grid items-center gap-12 pb-20 pt-16 lg:min-h-[760px] lg:grid-cols-[1.02fr_.98fr] lg:pt-12">
      <div><p className="eyebrow">Inteligencia artificial aplicada a negocios</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">Empleados Digitales que trabajan para tu empresa <span className="text-[var(--accent)]">24/7</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--muted)]">Automatizamos atención, ventas, citas y procesos internos con inteligencia artificial diseñada alrededor de tu negocio.</p><div className="mt-8 flex flex-wrap gap-3"><PrimaryCta/><Link href="/soluciones" className="inline-flex items-center gap-2 rounded-full border border-[var(--line)] bg-white px-5 py-3 text-sm font-semibold">Conocer las soluciones <ArrowUpRight size={16}/></Link></div><p className="mt-6 flex items-center gap-2 text-sm text-[var(--muted)]"><ShieldCheck size={16}/> Tecnología con supervisión humana y procesos trazables.</p></div>
      <HeroVisual/>
    </section>

    <section className="border-y border-[var(--line)] bg-white/55"><div className="container-shell grid grid-cols-2 gap-px md:grid-cols-4">{["Atención continua","Respuestas más rápidas","Procesos conectados","Supervisión humana"].map((v)=><div key={v} className="flex items-center gap-2 py-5 text-sm font-medium"><CircleDot size={14} className="text-[var(--accent)]"/>{v}</div>)}</div></section>

    <section className="container-shell section-pad grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">El problema</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Tu empresa no debería perder oportunidades por responder tarde</h2></div><div className="grid gap-3 sm:grid-cols-2">{problems.map((p)=><div key={p} className="card lift flex min-h-36 items-end p-6 text-lg font-semibold"><span className="mr-3 text-[var(--accent)]">→</span>{p}</div>)}</div></section>

    <section className="border-y border-[var(--line)] bg-white/50"><div className="container-shell section-pad"><p className="eyebrow">Soluciones</p><div className="mt-4 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="max-w-2xl text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Un equipo digital para cada parte del negocio</h2><Link href="/soluciones" className="text-sm font-semibold text-[var(--accent)]">Ver todas las soluciones →</Link></div><div className="mt-10 grid gap-4 md:grid-cols-2">{solutions.map((s,i)=><article key={s.title} className="card lift p-7"><div className="mb-8 grid h-10 w-10 place-items-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]">{[<MessagesSquare key="a"/>,<Route key="b"/>,<CalendarCheck key="c"/>,<Workflow key="d"/>][i]}</div><h3 className="text-xl font-semibold">{s.title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{s.description}</p></article>)}</div></div></section>

    <section className="container-shell section-pad"><p className="eyebrow">Cómo trabajamos</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Tecnología adaptada a tu operación, no al revés</h2><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{steps.map(([n,t,d])=><div key={n} className="border-t border-black pt-5"><span className="text-xs font-semibold text-[var(--accent)]">{n}</span><h3 className="mt-8 text-xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{d}</p></div>)}</div></section>

    <section className="border-y border-[var(--line)] bg-[#171717] text-white"><div className="container-shell section-pad"><p className="eyebrow !text-[#9ca9ff]">Casos de uso</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.045em] sm:text-5xl">IA útil donde la operación realmente lo necesita</h2><div className="mt-10 grid gap-3 md:grid-cols-2">{useCases.map((u)=><article key={u.title} className="rounded-2xl border border-white/15 bg-white/[.045] p-6"><h3 className="text-lg font-semibold">{u.title}</h3><p className="mt-3 leading-7 text-white/65">{u.description}</p></article>)}</div></div></section>

    <section className="container-shell section-pad grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">Producto</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Control humano, operación inteligente</h2><p className="mt-5 max-w-xl text-lg leading-8 text-[var(--muted)]">Un Empleado Digital no debería ser una caja negra. Diseñamos flujos donde tu equipo puede entender qué está ocurriendo y tomar el control cuando sea necesario.</p></div><div className="card overflow-hidden p-3"><div className="rounded-[1rem] bg-[#111] p-5 text-white"><div className="flex items-center justify-between"><div className="font-semibold">Centro de operaciones</div><div className="rounded-full bg-white/10 px-2 py-1 text-[10px] uppercase tracking-wider">Vista conceptual</div></div><div className="mt-5 grid grid-cols-2 gap-3">{[["Conversaciones","En curso"],["Derivaciones","Por revisar"],["Citas","Coordinadas"],["Actividad","Reciente"]].map(([a,b])=><div key={a} className="rounded-xl border border-white/10 bg-white/[.06] p-4"><p className="text-xs text-white/50">{a}</p><p className="mt-3 font-semibold">{b}</p></div>)}</div><div className="mt-3 rounded-xl border border-white/10 bg-white/[.06] p-4"><div className="flex items-center gap-2 text-sm"><Sparkles size={15} className="text-[#a7b1ff]"/> Empleado Digital activo</div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-3/4 rounded-full bg-[#8f9cff]"/></div></div></div></div></section>

    <section className="border-y border-[var(--line)] bg-white/55"><div className="container-shell section-pad grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">Beneficios</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Más capacidad sin aumentar la carga operativa</h2></div><div className="grid gap-3 sm:grid-cols-2">{benefits.map((b)=><div key={b} className="flex gap-3 rounded-xl border border-[var(--line)] bg-white p-4 text-sm"><Check size={18} className="shrink-0 text-[var(--success)]"/>{b}</div>)}</div></div></section>

    <section className="container-shell section-pad"><div className="relative overflow-hidden rounded-[2rem] bg-[var(--accent)] px-6 py-14 text-white sm:px-10 lg:px-16 lg:py-18"><Bot className="absolute -right-8 -top-8 h-48 w-48 text-white/[.06]"/><p className="text-xs font-semibold uppercase tracking-[.14em] text-white/70">Primer paso</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Convierte tus procesos repetitivos en una ventaja competitiva</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-white/75">Conversemos sobre el primer Empleado Digital que puede implementar tu empresa.</p><div className="mt-8"><PrimaryCta/></div></div></section>
  </>;
}
